import { Providers } from "@/redux/Provider";
import './globals.css'

export const metadata = {
	title: "HeyFoods",
	description: "Generated by create next app",
};
import { Inter } from 'next/font/google'
 
const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {
	return (
		<html lang='en' className={inter.className} >
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}

